import java.util.Scanner;

public class Aula8 {
    public static void main(String[] args) {
        //Faça a leitura de 30 pessoas e informe em numeros pares os registros
        String pessoa1, pessoa2, pessoa3, pessoa4, pessoa5, pessoa6, pessoa7, pessoa8, pessoa9, pessoa10, pessoa11, pessoa12, pessoa13, pessoa14, pessoa15, pessoa16, pessoa17, pessoa18, pessoa19, pessoa20, pessoa21, pessoa22, pessoa23, pessoa24, pessoa25, pessoa26, pessoa27, pessoa28, pessoa29, pessoa30;
        Scanner leitura = new Scanner(System.in);
        System.out.println("Digite o nome");
        pessoa1 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa2 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa3 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa4 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa5 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa6 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa7 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa8 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa9 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa10 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa11 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa12 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa13 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa14 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa15 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa16 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa17 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa18 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa19 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa20 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa21 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa22 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa23 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa24 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa25 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa26 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa27 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa28 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa29 = leitura.nextLine();
        System.out.println("Digite o nome");
        pessoa30 = leitura.nextLine();
        System.out.println(pessoa1);
        System.out.println(pessoa3);
        System.out.println(pessoa5);
        System.out.println(pessoa7);
        System.out.println(pessoa9);
        System.out.println(pessoa11);
        System.out.println(pessoa13);
        System.out.println(pessoa15);
        System.out.println(pessoa17);
        System.out.println(pessoa19);
        System.out.println(pessoa21);
        System.out.println(pessoa23);
        System.out.println(pessoa25);
        System.out.println(pessoa27);
        System.out.println(pessoa29);
    }    
}
